version: 2
jobs:
  bootstrap-build:
    docker:
      - image: codesmithy/gcc-bootstrap-build-prerequisites:0.1.0
    steps:
      - run: 
          name: "Set CODESMITHYIDE environment variables"
          command: echo 'export CODESMITHYIDE="/CodeSmithyIDE"' >> $BASH_ENV
      - checkout:
          path: /CodeSmithyIDE/Tasks
      - run:
          name: Build
          command: cd /CodeSmithyIDE/Tasks/Makefiles/GNUmakefile && make
      - run:
          name: Test build
          command: cd /CodeSmithyIDE/Tasks/Tests/Makefiles/GNUmakefile && make
      - run:
          name: Run the tests
          command: cd /CodeSmithyIDE/Tasks/Tests/Makefiles/GNUmakefile && ./CodeSmithyTasksTests
  build:
    docker:
      - image: codesmithy/gcc-build-prerequisites:0.1.0
    steps:
      - run:
          name: "Set CODESMITHYIDE environment variables"
          command: echo 'export CODESMITHYIDE="/CodeSmithyIDE"' >> $BASH_ENV
      - checkout:
          path: /CodeSmithyIDE/Tasks
      - run:
          name: Build
          command: cd /CodeSmithyIDE/Tasks/Makefiles/GNUmakefile && make
      - run:
          name: Test build
          command: cd /CodeSmithyIDE/Tasks/Tests/Makefiles/GNUmakefile && make
      - run:
          name: Run the tests
          command: cd /CodeSmithyIDE/Tasks/Tests/Makefiles/GNUmakefile && ./CodeSmithyTasksTests
workflows:
  version: 2
  build:
    jobs:
      - bootstrap-build
      - build
